# Generated by Django 5.0.6 on 2024-05-18 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.TextField()),
                ('turn', models.CharField(choices=[('R', 'Red'), ('Y', 'Yellow')], max_length=1)),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('finished', 'Finished')], max_length=10)),
                ('winner', models.CharField(choices=[('R', 'Red'), ('Y', 'Yellow'), ('N', 'None')], default='N', max_length=1)),
            ],
        ),
    ]
