# Generated by Django 5.0.6 on 2024-05-23 22:43

import games.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='turn',
            new_name='current_player',
        ),
        migrations.AlterField(
            model_name='game',
            name='board',
            field=models.JSONField(default=games.models.default_board),
        ),
    ]
